#!/bin/bash

INFILE=$1

if [ -z "$INFILE" ]; then
    echo "USAGE: psx-cuegen BINFILE"
    exit 1
fi

if [[ $INFILE != *.bin ]]; then
    echo "Input is not a .bin file!"
    exit 1
fi

INPATH=$(readlink -f $INFILE)

CUEFILE="$(basename "$INFILE" .bin).cue"
OUTPATH=$(readlink -f $CUEFILE)

BINBASENAME="$(basename $OUTPATH)"
echo "FILE \"$BINBASENAME\" BINARY" > $OUTPATH
echo "  TRACK 01 MODE2/2352" >> $OUTPATH
echo "    INDEX 01 00:00:00" >> $OUTPATH

echo "Cue file created successfully at '$OUTPATH'."
