#!/bin/bash

INFILE="$1"

if [ -z "$INFILE" ]; then
    echo "USAGE: psx-cuegen BINFILE"
    exit 1
fi

if [[ $INFILE != *.bin ]]; then
    echo "Input is not a .bin file!"
    exit 1
fi

echo "psx-cuegen - Copyright Jan Tuomi 2016"
echo "Input file: $INFILE"

CUEFILE="$(basename "$INFILE" .bin).cue"
echo "Cue file to be generated: $CUEFILE"

BINBASENAME="$(basename "$CUEFILE")"
echo "FILE \"$BINBASENAME\" BINARY" > "$CUEFILE"
echo "  TRACK 01 MODE2/2352" >> "$CUEFILE"
echo "    INDEX 01 00:00:00" >> "$CUEFILE"

echo "Cue file created successfully at '$CUEFILE'."
